name: Build and Deploy on Tag
on:
  push:
    tags:
      - "v*"

env:
  PACKAGE_AND_BREW: ${{ secrets.PACKAGE_AND_BREW }}
  VERSION: ${{ gitea.ref_name }}
  
jobs:
  build-ppc:
    name: "🔨 Build for PowerPC"
    runs-on: ubuntu-latest
    container: 
      image: git.tesses.org/tesses50/linux-ppc:latest
    steps:
      - uses: actions/checkout@v4
      - run: bash build-for-ppc.sh
      - uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          prerelease: true
          files: |-
            artifacts/** 

  build-packages:
    name: "🔨 Build for everything else"
    runs-on: fw13-ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - container: "git.tesses.org/tesses50/linux-x64:latest"
            nfpmName: "amd64"
            debianName: "x86_64-linux-gnu"
          - container: "git.tesses.org/tesses50/linux-x86:latest"
            nfpmName: "386"
            debianName: "i386-linux-gnu"
          - container: "git.tesses.org/tesses50/linux-arm:latest"
            nfpmName: "arm7"
            debianName: "arm-linux-gnueabihf"
          - container: "git.tesses.org/tesses50/linux-arm64:latest"
            nfpmName: "arm64"
            debianName: "aarch64-linux-gnu"
          - container: "git.tesses.org/tesses50/linux-riscv64:latest"
            nfpmName: "riscv64"
            debianName: "riscv64-linux-gnu"
            
    container: 
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - run: bash build-for-nfpm.sh ${{ matrix.nfpmName }} ${{ matrix.debianName }}
      - uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          prerelease: true
          files: |-
            artifacts/** 
  
  update-tap-and-build-win32:
    name: "🔨 Build win32 and update the tap 🍺"
    runs-on: global-container-mingw
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir artifacts
          env -C Packaging/WinToolsIntel bash build.sh

      - uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          prerelease: true
          files: |-
            artifacts/** 

      - uses: actions/checkout@v4
        with:
          ref: "master"
          path: "tapdir"
          repository: "tesses50/tesses-tap.git"
          token: ${{ env.PACKAGE_AND_BREW }}
      - run: |
          cd tapdir
          bash ../Packaging/edit-formula.sh
          git config user.name "Tesses Gitea Bot"
          git config user.email "noreply@tesses.net"
          git add .
          git commit -m "Push tessesframework=${{ env.VERSION }}"
          git push
